Fix bug (when self.interstitials is None, AttributeError happens) Case: When I try to make DefectSetEntryMaker, without any interstitial Error message: AttributeError: 'NoneType' object has no attribute 'keys'